ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/dnsmasq-$VER/sbin:$PATH

STOPSIGNAL SIGTERM

RUN set -ex;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  curl -sS -L -k -f http://repo/sw/opensource/dnsmasq/bin/dnsmasq-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv dnsmasq-$VER dnsmasq;\
  mkdir -pv etc/dnsmasq.d;\
  mkdir -pv /var/opt/tftp;\
  mkdir -pv /var/opt/dhcp;\
  ls -l /usr/local;\
  dnsmasq --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
