ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/openfortivpn-$VER/bin:$PATH

RUN set -ex;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install ppp;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
  fi;\
  cd /usr/local;\
  curl -sS -L -k -f http://repo/sw/opensource/openfortivpn/bin/openfortivpn-$VER-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv openfortivpn-$VER openfortivpn;\
  openfortivpn --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
