ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/registry-$VER:$PATH

RUN set -ex;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  mkdir -pv registry-$VER;\
  ln -snfv registry-$VER registry;\
  curl -sS -L -k -f http://repo/sw/opensource/registry/bin/registry_${VER}_linux_amd64.tar.gz | tar xzf - -C registry;\
  chown -R root:root registry-$VER;\
  mkdir -pv etc/registry;\
  mkdir -pv /var/opt/registry;\
  chown none:none /var/opt/registry;\
  ls -l /usr/local;\
  registry --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
  [ -f /tmp/vers.txt ] && (cat /tmp/vers.txt && rm -f /tmp/vers.txt) || true;\
 ) > /version.d/version-$REPO.txt;

ADD config/ /usr/local/etc/registry/
ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
