ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/maven/bin:$PATH
ENV M2_HOME /usr/local/maven

RUN set -ex;\
  cd /usr/local;\
  mkdir -pv maven-$VER;\
  ln -snfv maven-$VER maven;\
  curl -sS -L -k -f http://repo/sw/opensource/apache-maven/bin/apache-maven-$VER-bin.tar.gz | tar xzf - --strip-components=1 -C maven;\
  chown -R root:root maven-$VER;\
  touch /.bash_history_all;\
  chmod a+rw /.bash_history_all;\
  mvn -version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
