ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/certbot-$VER/bin:$PATH

RUN set -ex;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install build-essential python3-dev libffi-dev sqlite3 libssl-dev libxslt1-dev;\
    apt-get -yqq install libpq-dev python3-dev;\
    if expr match $OSN debian13; then\
      apt-get -yqq install python3-virtualenv python3-distutils-extra;\
    fi;\
    if expr match $OSN debian12; then\
      apt-get -yqq install python3-virtualenv python3-distutils python3-lib2to3;\
    fi;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
  fi;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  curl -sS -L -k -f http://repo/sw/opensource/certbot/bin/certbot-$VER-$OSN-venv.tar.gz | tar xzf -;\
  ln -snfv certbot-$VER certbot;\
  ln -snfv /usr/local/certbot/bin/certbot /usr/local/bin;\
  mkdir -pv /var/log/letsencrypt;\
  chown none:none /var/log/letsencrypt;\
  S=zlocal-certbot.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/101045-letsencrypt/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  ls -l /usr/local;\
  certbot --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
  [ -f /tmp/vers.txt ] && (cat /tmp/vers.txt && rm -f /tmp/vers.txt) || true;\
 ) > /version.d/version-$REPO.txt;
