ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/element-$VER:$PATH

RUN set -ex;\
  cd /usr/local;\
  curl -sS -L -k -f http://repo/sw/opensource/matrix/bin/element-v$VER.tar.gz | tar xzf -;\
  ln -snfv element-v$VER element;\
  cd element;\
  ln -sv /usr/local/etc/element/config.json .;\
  ls -l /usr/local;\
  cat /usr/local/element/version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
