ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/fwknop-$VER/bin:/usr/local/fwknop-$VER/sbin:$PATH
ENV LD_LIBRARY_PATH /usr/local/fwknop/lib

RUN set -ex;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install firewalld ebtables libpcap-dev libgpgme-dev tcpdump;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
    S=zlocal-firewalld.sh;\
    curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001630-debian11/files/$S\
      && (chmod a+x /etc/profile.d/$S)\
      || (echo Script $S not available);\
  fi;\
  if expr match $OSN centos; then\
    yum -y install firewalld tcpdump;\
    yum clean all;\
    S=zlocal-firewalld.sh;\
    curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001540-centos7/files/$S\
      && (chmod a+x /etc/profile.d/$S)\
      || (echo Script $S not available);\
  fi;\
  cd /usr/local;\
  mkdir -pv fwknop-$VER;\
  ln -snfv fwknop-$VER fwknop;\
  curl -sS -L -k -f http://repo/sw/opensource/fwknop/bin/fwknop-$VER-$OSN-$OSA.tar.gz | tar xzf - --strip-components=1 -C fwknop;\
  S=zlocal-fwknop.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/101100-fwknop//files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  ls -l /usr/local;\
  firewall-offline-cmd --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
