ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG TYPE
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV LANG=en_US.utf8
ENV TZ=Europe/Warsaw

ENV OS_NAME=debian13
ENV OS_ARCH=x86_64
ENV OS_CODE=trixie

ENV OSN=debian13
ENV OSA=x86_64
ENV OSC=trixie

ADD config/debian-$VER.list config/debian-$VER-updates.list config/debian-13-official.list.disabled /etc/apt/sources.list.d/

RUN set -ex;\
  touch /etc/apt/sources.list;\
  sed -i.b$(date +%Y%m%d) -e 's/^deb/#deb/' /etc/apt/sources.list;\
  mv -v /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.disabled;\
  grep ^[^#] /etc/apt/sources.list /etc/apt/sources.list.d/*;\
  export DEBIAN_FRONTEND=noninteractive;\
  apt-get update;\
  apt-get -yqq --no-install-recommends --no-install-suggests install locales locales-all libterm-readline-perl-perl;\
  localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8;\
  apt-get -yqq install net-tools iproute2 traceroute nmap lsof telnet iputils-ping;\
  apt-get -yqq install git curl wget unzip procps apt-utils debconf-utils;\
  apt-get -yqq install python3 python3-pkg-resources;\
  apt-get -yqq install jq vim xz-utils bsdextrautils jigdo-file man;\
  apt-get -yqq install apt-mirror debmirror gnupg xz-utils file tree;\
  apt-get -yqq install environment-modules gettext-base;\
  apt-get clean;\
  rm -rf /var/lib/apt/lists/*;\
  groupadd -g 666 none;\
  useradd -u 666 -g 666 -m -s /bin/bash none;\
  ln -snfv /usr/share/zoneinfo/$TZ /etc/localtime;\
  echo $TZ > /etc/timezone;\
  sed -i.b$(date +%Y%m%d) 's/PATH=\"/PATH=\"\$PATH:/' /etc/profile;\
  S=zlocal-0001.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001650-debian13/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-0002.bash;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001650-debian13/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-0010.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001650-debian13/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-ip.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001650-debian13/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=zlocal-apt.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001650-debian13/files/$S\
    && (chmod a+rx /etc/profile.d/$S)\
    || (echo Script $S not available);\
  S=vimrc.local;\
  curl -sS -L -k -f -o /etc/vim/${S} http://repo/pkb/pb/playbooks/001650-debian13/files/$S\
    && (chmod a+r /etc/vim/$S)\
    || (echo Script $S not available);\
  S=zlocal-readme.bash;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/001500-linux_admin/files/$S\
    && (chmod a+x /etc/profile.d/$S && mkdir -pv /usr/local/etc/doc)\
    || (echo Script $S not available);\
  S=zlocal-env-module.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/101630-env_module/files/$S\
    && (chmod a+x /etc/profile.d/$S && mkdir -pv /usr/local/etc/modulefiles && mkdir -pv /opt/local/etc/modulefiles)\
    || (echo Script $S not available);\
  S=zlocal-cdev-image.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/999210-cdev/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  cat /etc/os-release;\
  cat /etc/debian_version;

RUN set -ex;\
  export DEBIAN_FRONTEND=noninteractive;\
  apt-get update;\
  apt-get -yqq install python3-pip supervisor;\
  apt-get clean;\
  rm -rf /var/lib/apt/lists/*;\
  ln -sv /usr/local/etc/supervisord.conf /etc;\
  mkdir -pv /usr/local/etc/supervisord.d;\
  S=zlocal-supervisor.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/008330-supervisor/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  supervisord --version;

ADD config/supervisord.conf /usr/local/etc

RUN set -ex;\
  curl -sS -L -k -f -o /tini http://repo/sw/opensource/tini/bin/tini-amd64-current;\
  chmod a+x /tini;\
  /tini --version;

RUN set -ex;\
  mkdir -pv /cmd.d /version.d;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.type = ${TYPE:-[none]}";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]* /cmd.d/
ADD scripts/cmd.sh /
CMD ["/bin/bash","-l"]
