ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/mediamtx-$VER:$PATH

RUN set -ex;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq --no-install-recommends --no-install-suggests install ffmpeg;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
  fi;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  mkdir -pv mediamtx-$VER;\
  ln -snfv mediamtx-$VER mediamtx;\
  curl -sS -L -k -f http://repo/sw/opensource/mediamtx/bin/mediamtx_v${VER}_linux_amd64.tar.gz | tar xvzf - -C mediamtx;\
  chown -R root:root mediamtx-$VER;\
  mkdir -pv etc/mediamtx;\
  ln -snfv /usr/local/mediamtx/mediamtx.yml /usr/local/etc/mediamtx/mediamtx.yml;\
  ls -l /usr/local;\
  mediamtx --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
