ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG TYPE
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -ex;\
  cd /usr/local;\
  curl -sS -L -k -f http://repo/sw/opensource/hpl/bin/hpl-${VER}${TYPE:+-}${TYPE}-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv hpl-${VER}${TYPE:+-}${TYPE} hpl${TYPE:+-}${TYPE};\
  mkdir -pv /usr/local/etc/modulefiles/hpl;\
  S=hpl_config_N.sh;\
  curl -sS -L -k -f -o /usr/local/bin/$S http://repo/pkb/pb/playbooks/101364-hpc_benchmark/files/$S\
    && (chmod a+x /usr/local/bin/$S)\
    || (echo Script $S not available);\
  S=hpl-module-icc;\
  curl -sS -L -k -f -o /usr/local/etc/modulefiles/hpl/icc http://repo/pkb/pb/playbooks/101364-hpc_benchmark/files/$S\
    && (chmod a+r /usr/local/etc/modulefiles/hpl/icc)\
    || (echo Script $S not available);\
  ls -l /usr/local;

ADD scripts/xhpl.sh /usr/local/bin

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.type = ${TYPE:-[none]}";\
  echo "info.from = $FROM";\
  [ -f /tmp/vers.txt ] && (cat /tmp/vers.txt && rm -f /tmp/vers.txt) || true;\
 ) > /version.d/version-$REPO.txt;
