ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM

RUN set -ex;\
  cd /usr/local;\
  mkdir -pv wordpress-$VER;\
  ln -snfv wordpress-$VER wordpress;\
  curl -sS -L -k -f http://repo/sw/opensource/wordpress/wordpress-$VER.tar.gz | tar xzf - --strip-components=1 -C wordpress;\
  chown -R root:root wordpress-$VER;\
  cd wordpress;\
  mkdir -pv /var/opt/wordpress/wp-content/plugins /var/opt/wordpress/wp-content/themes;\
  mv -v wp-content wp-content.ORG;\
  ln -sv /var/opt/wordpress/wp-content .;\
  ln -sv /var/opt/wordpress/wp-config.php .;\
  if [ -f /usr/local/etc/php7/php.ini ]; then\
    sed -i.ORG -e 's/^;cgi.fix_pathinfo.*$/cgi.fix_pathinfo=0/' /usr/local/etc/php7/php.ini;\
  fi;\
  if [ -f /usr/local/etc/php8/php.ini ]; then\
    sed -i.ORG -e 's/^;cgi.fix_pathinfo.*$/cgi.fix_pathinfo=0/' /usr/local/etc/php8/php.ini;\
  fi;\
  V=$(curl -s http://repo/sw/opensource/wp-cli/bin/version.txt | grep ^wp-cli: | awk '{print $2}');\
  curl -sS -L -k -f -o /usr/local/bin/wp http://repo/sw/opensource/wp-cli/bin/wp-cli-$V.phar;\
  chmod a+x /usr/local/bin/wp;\
  echo "info.vers = wp-cli/$V" >> /tmp/vers.txt;\
  S=zlocal-wp-cli.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/101018-wordpress/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  ls -l /usr/local;\
  grep '^\$' /usr/local/wordpress/wp-includes/version.php;\
  su none -c "wp --path=/usr/local/wordpress core version --extra";

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
  [ -f /tmp/vers.txt ] && (cat /tmp/vers.txt && rm -f /tmp/vers.txt) || true;\
 ) > /version.d/version-$REPO.txt;
