ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/node/bin:$PATH

RUN set -ex;\
  groupadd -g 433 node;\
  useradd -u 433 -g 433 -c "Node.js" -m -s /bin/bash node;\
  cd /usr/local;\
  mkdir -pv node-$VER;\
  ln -snfv node-$VER node;\
  curl -sS -L -k -f http://repo/sw/opensource/node/bin/node-v$VER-linux-x64.tar.xz | tar xJf - --strip-components=1 -C node;\
  npm install --global yarn;\
  S=zlocal-node.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/101530-nodejs/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  npm --version;\
  yarn --version;\
  node --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
