ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/podman-exporter-$VER:$PATH

RUN set -ex;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq --allow-downgrades install libgpgme-dev libbtrfs-dev libdevmapper-dev libassuan-dev;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
  fi;\
  cd /usr/local;\
  mkdir -pv podman-exporter-$VER;\
  ln -snfv podman-exporter-$VER podman-exporter;\
  curl -sS -L -k -f http://repo/sw/opensource/prometheus/bin/podman-exporter-$VER-$OSN-$OSA.tar.gz | tar xvzf - --strip-components=1 -C podman-exporter;\
  chown -R root:root podman-exporter-$VER;\
  podman-exporter --version || true;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
