ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/go-$VER/bin:$PATH

RUN set -ex;\
  cd /usr/local;\
  mkdir -pv go-$VER;\
  ln -snfv go-$VER go;\
  curl -sS -L -k -f http://repo/sw/opensource/go/bin/go$VER.linux-amd64.tar.gz | tar xzf - --strip-components=1 -C go;\
  chown -R root:root go-$VER;\
  ls -l /usr/local;\
  go version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
