#!/bin/bash

[[ -z $SLURM_EXPORTER_LISTEN_ADDRESS ]] && SLURM_EXPORTER_LISTEN_ADDRESS="0.0.0.0:8080"
[[ -z $SLURM_EXPORTER_API_URL        ]] && SLURM_EXPORTER_API_URL="127.0.0.1:6820"
[[ -z $SLURM_EXPORTER_API_USER       ]] && SLURM_EXPORTER_API_USER="root"
[[ -z $SLURM_EXPORTER_API_TOKEN      ]] && SLURM_EXPORTER_API_TOKEN="1234"

export SLURM_EXPORTER_LISTEN_ADDRESS
export SLURM_EXPORTER_API_URL
export SLURM_EXPORTER_API_USER
export SLURM_EXPORTER_API_TOKEN

echo "env config:"
echo "    SLURM_EXPORTER_LISTEN_ADDRESS = $SLURM_EXPORTER_LISTEN_ADDRESS"
echo "    SLURM_EXPORTER_API_URL        = $SLURM_EXPORTER_API_URL"
echo "    SLURM_EXPORTER_API_USER       = $SLURM_EXPORTER_API_USER"
echo "    SLURM_EXPORTER_API_TOKEN      = $SLURM_EXPORTER_API_TOKEN"
echo

set -x
exec setpriv --reuid=666 --regid=666 --clear-groups --no-new-privs \
  slurm-exporter
