ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/minio-$VER:$PATH

RUN set -ex;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  mkdir -pv minio-$VER;\
  ln -snfv minio-$VER minio;\
  curl -sS -L -k -f -o minio/minio http://repo/sw/opensource/minio/bin/minio-$VER;\
  curl -sS -L -k -f -o minio/mc http://repo/sw/opensource/minio/bin/mc;\
  chmod a+x minio/m*;\
  mkdir -pv /var/opt/minio/main;\
  chown none:none /var/opt/minio/main;\
  minio --version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
CMD ["/cmd.sh"]
