ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/jdk-$VER/bin:$PATH
ENV JAVA_HOME /usr/local/jdk-$VER

RUN set -ex;\
  if expr match $VER 11; then\
    yum -y install java-11-openjdk java-11-openjdk-devel;\
    yum clean all;\
    ln -sv /usr /usr/local/jdk-$VER;\
  elif expr match $VER 1.8; then\
    yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel;\
    yum clean all;\
    ln -sv /usr /usr/local/jdk-$VER;\
  else \
    cd /usr/local;\
    mkdir -pv jdk-$VER;\
    ln -snfv jdk-$VER jdk-${VER%%.*};\
    curl -sS -L -k -f http://repo/sw/opensource/openjdk/bin/openjdk-${VER}_linux-x64_bin.tar.gz | tar xzf - --strip-components=1 -C jdk-$VER;\
    chown -R root:root jdk-${VER};\
    yum -y install freetype alsa-lib libXext libX11 libXrender libXtst libXi;\
    yum -y install fontconfig dejavu-sans-fonts;\
    yum clean all;\
  fi; \
  ls -l /usr/local;\
  java -version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
