ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/jdk-$VER/bin:$PATH
ENV JAVA_HOME /usr/local/jdk-$VER

RUN set -ex;\
  if expr match $VER 17; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install openjdk-17-jre openjdk-17-jdk;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
    ln -sv /usr/lib/jvm/java-17-openjdk-amd64 /usr/local/jdk-$VER;\
  elif expr match $VER 11; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install openjdk-11-jre openjdk-11-jdk;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
    ln -sv /usr/lib/jvm/java-11-openjdk-amd64 /usr/local/jdk-$VER;\
  else\
    cd /usr/local;\
    mkdir -pv jdk-$VER;\
    ln -snfv jdk-$VER jdk-${VER%%.*};\
    curl -sS -L -k -f http://repo/sw/opensource/openjdk/bin/openjdk-${VER}_linux-x64_bin.tar.gz | tar xzf - --strip-components=1 -C jdk-$VER;\
    chown -R root:root jdk-$VER;\
  fi;\
  ls -l /usr/local;\
  java -version;

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
