ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/fdroidserver-$VER/bin:$PATH

RUN set -ex;\
  if expr match $OSN debian; then\
    export DEBIAN_FRONTEND=noninteractive;\
    apt-get update;\
    apt-get -yqq install apksigner rsync;\
    if expr match $OSN debian13; then\
      apt-get -yqq install openjdk-21-jre openjdk-21-jdk;\
      apt-get -yqq install python3-virtualenv python3-distutils-extra;\
    fi;\
    if expr match $OSN debian12; then\
      apt-get -yqq install openjdk-17-jre openjdk-17-jdk;\
      apt-get -yqq install python3-virtualenv python3-distutils python3-lib2to3;\
    fi;\
    apt-get clean;\
    rm -rf /var/lib/apt/lists/*;\
  fi;\
  [ -z "$(id -g none)" ] && groupadd -g 666 none;\
  [ -z "$(id -u none)" ] && useradd -u 666 -g 666 -m -s /bin/bash none;\
  cd /usr/local;\
  curl -sS -L -k -f http://repo/sw/opensource/fdroidserver/bin/fdroidserver-$VER-$OSN-venv.tar.gz | tar xzf -;\
  ln -snfv fdroidserver-$VER fdroidserver;\
  chown -R none:none fdroidserver-$VER;\
  ln -snfv /usr/local/fdroidserver/bin/activate /usr/local/bin;\
  ln -snfv /usr/local/fdroidserver/bin/fdroid /usr/local/bin;\
  mkdir -pv /var/opt/fdroidserver;\
  chown -R none:none /var/opt/fdroidserver;\
  touch /.bash_history_all;\
  chmod a+rw /.bash_history_all;\
  S=zlocal-fdroidserver.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/004910-fdroid/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  ls -l /usr/local;\
  fdroid --version;

WORKDIR /var/opt/fdroidserver

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;
