ARG FROM
FROM $FROM

ARG DATE
ARG FROM
ARG REPO
ARG VER

LABEL info.from="$FROM"
LABEL info.name="$REPO:$VER"
LABEL info.date="$DATE"

ENV INFO_DATE=$DATE INFO_REPO=$REPO INFO_VER=$VER INFO_FROM=$FROM
ENV PATH /usr/local/openvpn-$VER+x/sbin:$PATH
ENV LD_LIBRARY_PATH /usr/local/openssl+x/lib64

RUN set -ex;\
  mv -v /cmd.d/190-ep-supervisord.sh.disabled /cmd.d/190-ep-supervisord.sh;\
  if expr match $OSN centos; then\
    yum -y install lzo lz4;\
    yum clean all;\
  fi;\
  cd /usr/local;\
  V=$(curl -s http://repo/sw/opensource/openssl/bin/version.txt | grep ^openssl: | awk '{print $2}');\
  curl -sS -L -k -f http://repo/sw/opensource/openssl/bin/openssl-$V+x-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv openssl-$V+x openssl+x;\
  chown -R root:root openssl-$V+x;\
  curl -sS -L -k -f http://repo/sw/opensource/openvpn/bin/openvpn-$VER+x-$OSN-$OSA.tar.gz | tar xzf -;\
  ln -snfv openvpn-$VER+x openvpn+x;\
  chown -R root:root openvpn-$VER+x;\
  mkdir -pv /usr/local/etc/openvpn;\
  S=zlocal-openvpn.sh;\
  curl -sS -L -k -f -o /etc/profile.d/$S http://repo/pkb/pb/playbooks/101050-openvpn/files/$S\
    && (chmod a+x /etc/profile.d/$S)\
    || (echo Script $S not available);\
  /usr/local/openssl+x/bin/openssl version;\
  openvpn --version|fold -w 60 -s;

ADD scripts/openvpn-log.sh /usr/local/bin/

RUN set -ex;\
 (echo "info.date = $DATE";\
  echo "info.name = $REPO:$VER";\
  echo "info.from = $FROM";\
 ) > /version.d/version-$REPO.txt;

ADD scripts/[0-9]*.sh /cmd.d/
ADD supervisord/*.conf /usr/local/etc/supervisord.d/
CMD ["/cmd.sh"]
